### ISSUE TITLE
It all stops working after a while on Catalina

### ISSUE THREAD

**Issue by AKarbas** [pqrs-org/Karabiner-Elements#2089]
Hi.

I'm using Karabiner Elements on Catalina (10.15.1 (19B88)) on an iMac (Installed with `brew cask` and then updated to the beta version.) with Microsoft's Sculpt Ergonomic Keyboard Surface Edition.

This has happened twice, where after the first time, I had to uninstall Karabiner, remove all of its files, and then reinstall and re-configure it:
I set up the app, and configure all my modifications to both the keyboard and the mouse.
Then, after a while (first time took about a month or two and the second time took a week or two.) suddenly my mouse and keyboard stop working.
Then, I have to detach and re-attach the USB dongle and then they work and the new keyboard setup screen comes up, and none of the modifications are working.

Please help for I really love this keyboard+mouse but can't use them on mac without some mods!

P.s. pointing me in the direction of a whole other solution to do these mods would also be appreciated.

**Comment by OItsMAK** [comment]
Also, I don't see much in the logs, there are a bunch of device terminated/matching in there which are from when I was de/re-attaching the dongle a bunch of times.

<details> 
<summary>Logs</summary>

```Bash
[2019-12-03 20:53:54.511] [info] [observer]   product_id: 1957
[2019-12-03 20:53:54.512] [info] [observer]   location_id: 0x14600000
[2019-12-03 20:53:54.513] [info] [observer]   is_keyboard: true
[2019-12-03 20:53:54.513] [info] [observer]   is_pointing_device: false
[2019-12-03 20:53:54.513] [info] [observer] rescan devices...
[2019-12-03 20:53:54.513] [info] [observer] grabber_client is connected.
[2019-12-03 20:53:54.513] [info] [observer] rescan devices...
[2019-12-03 20:53:54.513] [info] [observer] matching device:
[2019-12-03 20:53:54.513] [info] [observer]   registry_entry_id: 4294968111
[2019-12-03 20:53:54.513] [info] [observer]   manufacturer: Microsoft
[2019-12-03 20:53:54.513] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-03 20:53:54.513] [info] [observer]   vendor_id: 1118
[2019-12-03 20:53:54.513] [info] [observer]   product_id: 1957
[2019-12-03 20:53:54.513] [info] [observer]   location_id: 0x14600000
[2019-12-03 20:53:54.514] [info] [observer]   is_keyboard: false
[2019-12-03 20:53:54.514] [info] [observer]   is_pointing_device: true
[2019-12-03 20:53:54.514] [info] [observer] rescan devices...
[2019-12-03 20:53:54.514] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294968104) is observed.
[2019-12-03 20:53:54.514] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294968111) is observed.
[2019-12-03 20:54:03.015] [info] [kextd] KextManagerLoadKextWithURL: kOSReturnSuccess
[2019-12-03 20:54:31.475] [info] [session_monitor] version 12.8.0
[2019-12-03 20:54:31.480] [info] [console_user_server] version 12.8.0
[2019-12-03 20:54:31.539] [info] [session_monitor] receiver is initialized
[2019-12-03 20:54:31.539] [info] [session_monitor] session_monitor_receiver_client is started.
[2019-12-03 20:54:31.541] [info] [grabber] current_console_user_id: 501
[2019-12-03 20:54:31.541] [info] [session_monitor] on_console_changed: true
[2019-12-03 20:54:31.541] [info] [session_monitor] receiver: bound
[2019-12-03 20:54:31.541] [info] [session_monitor] session_monitor_receiver_client is connected.
[2019-12-03 20:54:31.542] [info] [grabber] receiver is terminated
[2019-12-03 20:54:31.542] [info] [grabber] receiver is initialized
[2019-12-03 20:54:31.542] [info] [grabber] receiver: bound
[2019-12-03 20:54:31.542] [info] [grabber] receiver: chown socket: 501
[2019-12-03 20:54:31.909] [info] [console_user_server] receiver is initialized
[2019-12-03 20:54:31.910] [info] [console_user_server] receiver: bound
[2019-12-03 20:54:31.910] [info] [console_user_server] grabber_client is started.
[2019-12-03 20:54:31.910] [info] [console_user_server] grabber_client is connected.
[2019-12-03 20:54:32.730] [error] [observer] grabber_client error: Connection reset by peer
[2019-12-03 20:54:32.731] [info] [observer] grabber_client is closed.
[2019-12-03 20:54:33.733] [info] [observer] grabber_client is connected.
[2019-12-03 20:54:33.733] [info] [observer] rescan devices...
[2019-12-03 20:54:50.701] [info] [grabber] karabiner_console_user_server is connected.
[2019-12-03 20:54:50.702] [info] [grabber] console_user_server_client is connected. (uid:501)
[2019-12-03 20:54:50.702] [info] [grabber] device_grabber is started.
[2019-12-03 20:54:50.710] [info] [grabber] event_tap_monitor initialized
[2019-12-03 20:54:50.711] [info] [grabber] virtual_hid_device_client is started.
[2019-12-03 20:54:50.711] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-03 20:54:50.712] [info] [grabber] core_configuration is updated.
[2019-12-03 20:54:50.714] [info] [grabber] virtual_hid_device_client is opened.
[2019-12-03 20:54:50.715] [info] [grabber] virtual_hid_device_client_ is connected
[2019-12-03 20:54:50.715] [info] [grabber] initialize_virtual_hid_keyboard
[2019-12-03 20:54:50.715] [info] [grabber]   country_code:0
[2019-12-03 20:54:50.763] [info] [observer] matching device:
[2019-12-03 20:54:50.763] [info] [observer]   registry_entry_id: 4294969021
[2019-12-03 20:54:50.763] [info] [observer]   manufacturer: pqrs.org
[2019-12-03 20:54:50.763] [info] [observer]   product: Karabiner VirtualHIDKeyboard
[2019-12-03 20:54:50.763] [info] [observer]   vendor_id: 5824
[2019-12-03 20:54:50.763] [info] [observer]   product_id: 10203
[2019-12-03 20:54:50.763] [info] [observer]   location_id: 0x0
[2019-12-03 20:54:50.763] [info] [observer]   serial_number: pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v061000
[2019-12-03 20:54:50.785] [info] [observer]   is_keyboard: true
[2019-12-03 20:54:50.786] [info] [observer]   is_pointing_device: false
[2019-12-03 20:54:50.787] [info] [observer] rescan devices...
[2019-12-03 20:54:50.792] [info] [observer] Karabiner VirtualHIDKeyboard (device_id:4294969021) is observed.
[2019-12-03 20:54:50.792] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-03 20:54:50.793] [info] [grabber] `system_preferences` is updated.
[2019-12-03 20:54:50.793] [info] [console_user_server] core_configuration is updated.
[2019-12-03 20:54:50.809] [info] [console_user_server] Check for updates...
[2019-12-03 20:54:51.728] [info] [grabber] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294968104) is grabbed.
[2019-12-04 16:12:15.008] [info] [grabber] Re-enable event_tap_ by kCGEventTapDisabledByTimeout
[2019-12-04 16:30:32.072] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:30:32.082] [info] [grabber] core_configuration is updated.
[2019-12-04 16:30:32.098] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:30:32.119] [info] [observer] matching device:
[2019-12-04 16:30:32.137] [info] [console_user_server] core_configuration is updated.
[2019-12-04 16:30:32.142] [info] [observer]   registry_entry_id: 4294971412
[2019-12-04 16:30:32.142] [info] [observer]   manufacturer: pqrs.org
[2019-12-04 16:30:32.142] [info] [observer]   product: Karabiner VirtualHIDPointing
[2019-12-04 16:30:32.142] [info] [observer]   vendor_id: 5824
[2019-12-04 16:30:32.142] [info] [observer]   product_id: 10202
[2019-12-04 16:30:32.142] [info] [observer]   location_id: 0x0
[2019-12-04 16:30:32.142] [info] [observer]   serial_number: pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDPointing_v061000
[2019-12-04 16:30:32.143] [info] [observer]   is_keyboard: false
[2019-12-04 16:30:32.143] [info] [observer]   is_pointing_device: true
[2019-12-04 16:30:32.159] [info] [observer] rescan devices...
[2019-12-04 16:30:32.160] [info] [observer] Karabiner VirtualHIDPointing (device_id:4294971412) is observed.
[2019-12-04 16:30:44.759] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:30:44.759] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:30:44.760] [info] [grabber] core_configuration is updated.
[2019-12-04 16:30:44.760] [info] [console_user_server] core_configuration is updated.
[2019-12-04 16:30:44.761] [info] [observer] device_id:4294971412 is terminated.
[2019-12-04 16:30:44.786] [info] [observer] rescan devices...
[2019-12-04 16:30:51.336] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:30:51.336] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:30:51.337] [info] [grabber] core_configuration is updated.
[2019-12-04 16:30:51.337] [info] [console_user_server] core_configuration is updated.
[2019-12-04 16:30:51.340] [info] [grabber] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294968111) is grabbed.
[2019-12-04 16:30:51.341] [info] [observer] matching device:
[2019-12-04 16:30:51.341] [info] [observer]   registry_entry_id: 4294971421
[2019-12-04 16:30:51.341] [info] [observer]   manufacturer: pqrs.org
[2019-12-04 16:30:51.341] [info] [observer]   product: Karabiner VirtualHIDPointing
[2019-12-04 16:30:51.341] [info] [observer]   vendor_id: 5824
[2019-12-04 16:30:51.341] [info] [observer]   product_id: 10202
[2019-12-04 16:30:51.341] [info] [observer]   location_id: 0x0
[2019-12-04 16:30:51.341] [info] [observer]   serial_number: pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDPointing_v061000
[2019-12-04 16:30:51.342] [info] [observer]   is_keyboard: false
[2019-12-04 16:30:51.342] [info] [observer]   is_pointing_device: true
[2019-12-04 16:30:51.343] [info] [observer] rescan devices...
[2019-12-04 16:30:51.343] [info] [observer] Karabiner VirtualHIDPointing (device_id:4294971421) is observed.
[2019-12-04 16:31:00.053] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:31:00.054] [info] [grabber] core_configuration is updated.
[2019-12-04 16:31:00.054] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:31:00.055] [info] [console_user_server] core_configuration is updated.
[2019-12-04 16:31:10.590] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:31:10.590] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:31:10.591] [info] [grabber] core_configuration is updated.
[2019-12-04 16:31:10.591] [info] [console_user_server] core_configuration is updated.
[2019-12-04 16:31:19.542] [info] [grabber] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:31:19.542] [info] [console_user_server] Load /Users/mohammadamink/.config/karabiner/karabiner.json...
[2019-12-04 16:31:19.543] [info] [grabber] core_configuration is updated.
[2019-12-04 16:31:19.543] [info] [console_user_server] core_configuration is updated.
[2019-12-08 14:03:44.279] [info] [observer] device_id:4294968111 is terminated.
[2019-12-08 14:03:44.281] [info] [observer] rescan devices...
[2019-12-08 14:03:44.281] [info] [observer] device_id:4294968104 is terminated.
[2019-12-08 14:03:44.281] [info] [observer] rescan devices...
[2019-12-08 14:04:13.547] [info] [observer] matching device:
[2019-12-08 14:04:13.547] [info] [observer]   registry_entry_id: 4294980322
[2019-12-08 14:04:13.558] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:04:13.558] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:04:13.558] [info] [observer]   vendor_id: 1118
[2019-12-08 14:04:13.558] [info] [observer]   product_id: 1957
[2019-12-08 14:04:13.558] [info] [observer]   location_id: 0x14100000
[2019-12-08 14:04:13.818] [info] [observer]   is_keyboard: false
[2019-12-08 14:04:13.818] [info] [observer]   is_pointing_device: true
[2019-12-08 14:04:13.818] [info] [observer] rescan devices...
[2019-12-08 14:04:13.818] [info] [observer] matching device:
[2019-12-08 14:04:13.818] [info] [observer]   registry_entry_id: 4294980316
[2019-12-08 14:04:13.818] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:04:13.818] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:04:13.818] [info] [observer]   vendor_id: 1118
[2019-12-08 14:04:13.818] [info] [observer]   product_id: 1957
[2019-12-08 14:04:13.818] [info] [observer]   location_id: 0x14100000
[2019-12-08 14:04:13.818] [info] [observer]   is_keyboard: true
[2019-12-08 14:04:13.819] [info] [observer]   is_pointing_device: false
[2019-12-08 14:04:13.819] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980322) is observed.
[2019-12-08 14:04:13.819] [info] [observer] rescan devices...
[2019-12-08 14:04:13.819] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980316) is observed.
[2019-12-08 14:04:14.940] [info] [observer] matching device:
[2019-12-08 14:04:14.940] [info] [observer]   registry_entry_id: 4294980375
[2019-12-08 14:04:14.940] [info] [observer]   manufacturer: MOSART Semi.
[2019-12-08 14:04:14.940] [info] [observer]   product: 2.4G Keyboard Mouse
[2019-12-08 14:04:14.940] [info] [observer]   vendor_id: 1578
[2019-12-08 14:04:14.940] [info] [observer]   product_id: 16770
[2019-12-08 14:04:14.941] [info] [observer]   location_id: 0x14200000
[2019-12-08 14:04:14.941] [info] [observer]   is_keyboard: true
[2019-12-08 14:04:14.941] [info] [observer]   is_pointing_device: false
[2019-12-08 14:04:14.942] [info] [observer] rescan devices...
[2019-12-08 14:04:14.942] [info] [observer] 2.4G Keyboard Mouse (device_id:4294980375) is observed.
[2019-12-08 14:04:14.952] [info] [observer] matching device:
[2019-12-08 14:04:14.952] [info] [observer]   registry_entry_id: 4294980379
[2019-12-08 14:04:14.952] [info] [observer]   manufacturer: MOSART Semi.
[2019-12-08 14:04:14.953] [info] [observer]   product: 2.4G Keyboard Mouse
[2019-12-08 14:04:14.953] [info] [observer]   vendor_id: 1578
[2019-12-08 14:04:14.953] [info] [observer]   product_id: 16770
[2019-12-08 14:04:14.953] [info] [observer]   location_id: 0x14200000
[2019-12-08 14:04:14.954] [info] [observer]   is_keyboard: false
[2019-12-08 14:04:14.954] [info] [observer]   is_pointing_device: true
[2019-12-08 14:04:14.954] [info] [observer] rescan devices...
[2019-12-08 14:04:14.957] [info] [observer] 2.4G Keyboard Mouse (device_id:4294980379) is observed.
[2019-12-08 14:04:38.338] [info] [observer] device_id:4294980375 is terminated.
[2019-12-08 14:04:38.338] [info] [observer] device_id:4294980379 is terminated.
[2019-12-08 14:04:38.339] [info] [observer] rescan devices...
[2019-12-08 14:04:38.339] [info] [observer] rescan devices...
[2019-12-08 14:13:27.879] [info] [observer] device_id:4294980316 is terminated.
[2019-12-08 14:13:27.882] [info] [observer] device_id:4294980322 is terminated.
[2019-12-08 14:13:27.888] [info] [observer] rescan devices...
[2019-12-08 14:13:27.888] [info] [observer] rescan devices...
[2019-12-08 14:13:31.233] [info] [observer] matching device:
[2019-12-08 14:13:31.233] [info] [observer]   registry_entry_id: 4294980524
[2019-12-08 14:13:31.233] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:13:31.233] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:13:31.233] [info] [observer]   vendor_id: 1118
[2019-12-08 14:13:31.233] [info] [observer]   product_id: 1957
[2019-12-08 14:13:31.233] [info] [observer]   location_id: 0x14200000
[2019-12-08 14:13:31.234] [info] [observer]   is_keyboard: true
[2019-12-08 14:13:31.234] [info] [observer]   is_pointing_device: false
[2019-12-08 14:13:31.234] [info] [observer] rescan devices...
[2019-12-08 14:13:31.235] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980524) is observed.
[2019-12-08 14:13:31.253] [info] [observer] matching device:
[2019-12-08 14:13:31.253] [info] [observer]   registry_entry_id: 4294980530
[2019-12-08 14:13:31.254] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:13:31.254] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:13:31.254] [info] [observer]   vendor_id: 1118
[2019-12-08 14:13:31.254] [info] [observer]   product_id: 1957
[2019-12-08 14:13:31.254] [info] [observer]   location_id: 0x14200000
[2019-12-08 14:13:31.254] [info] [observer]   is_keyboard: false
[2019-12-08 14:13:31.255] [info] [observer]   is_pointing_device: true
[2019-12-08 14:13:31.255] [info] [observer] rescan devices...
[2019-12-08 14:13:31.257] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980530) is observed.
[2019-12-08 14:13:41.482] [info] [observer] device_id:4294980524 is terminated.
[2019-12-08 14:13:41.485] [info] [observer] rescan devices...
[2019-12-08 14:13:41.485] [info] [observer] device_id:4294980530 is terminated.
[2019-12-08 14:13:41.487] [info] [observer] rescan devices...
[2019-12-08 14:13:46.994] [info] [observer] matching device:
[2019-12-08 14:13:46.994] [info] [observer]   registry_entry_id: 4294980590
[2019-12-08 14:13:46.994] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:13:46.994] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:13:46.994] [info] [observer]   vendor_id: 1118
[2019-12-08 14:13:46.994] [info] [observer]   product_id: 1957
[2019-12-08 14:13:46.994] [info] [observer]   location_id: 0x14600000
[2019-12-08 14:13:46.994] [info] [observer]   is_keyboard: true
[2019-12-08 14:13:46.995] [info] [observer]   is_pointing_device: false
[2019-12-08 14:13:46.995] [info] [observer] rescan devices...
[2019-12-08 14:13:46.996] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980590) is observed.
[2019-12-08 14:13:47.007] [info] [observer] matching device:
[2019-12-08 14:13:47.007] [info] [observer]   registry_entry_id: 4294980594
[2019-12-08 14:13:47.007] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:13:47.007] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:13:47.007] [info] [observer]   vendor_id: 1118
[2019-12-08 14:13:47.007] [info] [observer]   product_id: 1957
[2019-12-08 14:13:47.007] [info] [observer]   location_id: 0x14600000
[2019-12-08 14:13:47.007] [info] [observer]   is_keyboard: false
[2019-12-08 14:13:47.007] [info] [observer]   is_pointing_device: true
[2019-12-08 14:13:47.007] [info] [observer] rescan devices...
[2019-12-08 14:13:47.008] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980594) is observed.
[2019-12-08 14:13:51.740] [info] [observer] device_id:4294980590 is terminated.
[2019-12-08 14:13:51.750] [info] [observer] rescan devices...
[2019-12-08 14:13:51.750] [info] [observer] device_id:4294980594 is terminated.
[2019-12-08 14:13:51.751] [info] [observer] rescan devices...
[2019-12-08 14:14:07.513] [info] [observer] matching device:
[2019-12-08 14:14:07.513] [info] [observer]   registry_entry_id: 4294980659
[2019-12-08 14:14:07.513] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:14:07.513] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:14:07.513] [info] [observer]   vendor_id: 1118
[2019-12-08 14:14:07.513] [info] [observer]   product_id: 1957
[2019-12-08 14:14:07.513] [info] [observer]   location_id: 0x14100000
[2019-12-08 14:14:07.513] [info] [observer]   is_keyboard: true
[2019-12-08 14:14:07.513] [info] [observer]   is_pointing_device: false
[2019-12-08 14:14:07.516] [info] [observer] rescan devices...
[2019-12-08 14:14:07.521] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980659) is observed.
[2019-12-08 14:14:07.523] [info] [observer] matching device:
[2019-12-08 14:14:07.523] [info] [observer]   registry_entry_id: 4294980663
[2019-12-08 14:14:07.523] [info] [observer]   manufacturer: Microsoft
[2019-12-08 14:14:07.523] [info] [observer]   product: MicrosoftÆ 2.4GHz Transceiver v9.0
[2019-12-08 14:14:07.523] [info] [observer]   vendor_id: 1118
[2019-12-08 14:14:07.523] [info] [observer]   product_id: 1957
[2019-12-08 14:14:07.523] [info] [observer]   location_id: 0x14100000
[2019-12-08 14:14:07.523] [info] [observer]   is_keyboard: false
[2019-12-08 14:14:07.523] [info] [observer]   is_pointing_device: true
[2019-12-08 14:14:07.523] [info] [observer] rescan devices...
[2019-12-08 14:14:07.524] [info] [observer] MicrosoftÆ 2.4GHz Transceiver v9.0 (device_id:4294980663) is observed.

```
</details>

<details>
<summary>~/.config/karabiner.json</summary>

```JSON
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": false,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": []
            },
            "devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": false,
                        "is_pointing_device": true,
                        "product_id": 1957,
                        "vendor_id": 1118
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": false,
                    "simple_modifications": []
                }
            ],
            "fn_function_keys": [
                {
                    "from": {
                        "key_code": "f1"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f2"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": {
                        "key_code": "mission_control"
                    }
                },
                {
                    "from": {
                        "key_code": "f4"
                    },
                    "to": {
                        "key_code": "launchpad"
                    }
                },
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": {
                        "key_code": "illumination_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f6"
                    },
                    "to": {
                        "key_code": "illumination_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f7"
                    },
                    "to": {
                        "consumer_key_code": "rewind"
                    }
                },
                {
                    "from": {
                        "key_code": "f8"
                    },
                    "to": {
                        "consumer_key_code": "play_or_pause"
                    }
                },
                {
                    "from": {
                        "key_code": "f9"
                    },
                    "to": {
                        "consumer_key_code": "fastforward"
                    }
                },
                {
                    "from": {
                        "key_code": "f10"
                    },
                    "to": {
                        "consumer_key_code": "mute"
                    }
                },
                {
                    "from": {
                        "key_code": "f11"
                    },
                    "to": {
                        "consumer_key_code": "volume_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f12"
                    },
                    "to": {
                        "consumer_key_code": "volume_increment"
                    }
                }
            ],
            "name": "Default profile",
            "parameters": {
                "delay_milliseconds_before_open_device": 1000
            },
            "selected": true,
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "application"
                    },
                    "to": {
                        "key_code": "right_command"
                    }
                },
                {
                    "from": {
                        "key_code": "insert"
                    },
                    "to": {
                        "key_code": "return_or_enter"
                    }
                },
                {
                    "from": {
                        "key_code": "print_screen"
                    },
                    "to": {
                        "consumer_key_code": "fastforward"
                    }
                },
                {
                    "from": {
                        "key_code": "right_gui"
                    },
                    "to": {
                        "key_code": "mission_control"
                    }
                },
                {
                    "from": {
                        "pointing_button": "button4"
                    },
                    "to": {
                        "key_code": "return_or_enter"
                    }
                }
            ],
            "virtual_hid_keyboard": {
                "country_code": 0,
                "mouse_key_xy_scale": 100
            }
        }
    ]
}
```
</summary>

**Comment by kurtguenther** [comment]
I have the same issue (same keyboard, same problem)

**Comment by SLED-5** [comment]
I have this issue too.

**Comment by lavandongen** [comment]
I have the same issue, for several days now, and it happened twice this morning. Very annoying and only fixed with a full restart of my Laptop

**Comment by wmertens** [comment]
For me on Catalina, Karabiner no longer applies complex modifications for Terminal.app and it also stops turning off the internal keyboard when my BT keyboard is connected.

So it seems like Karabiner just stops working, perhaps due to a bug in Catalina with keyboard grabbing?

**Comment by wmertens** [comment]
I had quit karabiner and started it a bit later and it's now all working again, so that looks like a workaround.

**Comment by sgsayson** [comment]
I have the same issue. Force-closing works, but hotkeys do not work after restarting application. Reboot restores functionality.

**Comment by GhostToast** [comment]
I have been having this issue the past week or so, and it seems to be related to hitting CAPS LOCK too quickly next to other keypresses. It will halt all keyboard input until I unplug and replug the external keyboard. But then my mappings are inactive seemingly unless I reboot.

**Comment by iay** [comment]
I have the same behaviour as @GhostToast above, except in my case it's an Apple Bluetooth keyboard. The only thing I have mapped at the moment is the Caps Lock to C+C+O+S if pressed with other keys complex modification. When it stops working, the caps lock light will be on.

Power cycling the keyboard brings the keyboard back to life but the mapping no longer works.

Reboot does seem to work, but restarting KE, or removing and re-enabling the mapping, does not.

**Comment by siddharthalodha** [comment]
> with

How do you power cycle the keyboard ? Does it require a reboot ?

**Comment by iay** [comment]
I have the Apple "Magic Keyboard with Numeric Keypad". It has a little power switch on the back, so you can just turn it off and turn it back on again independently of the computer. As I say, that seems to fix the "stuck caps lock" issue but at the cost of KE no longer work after that.

**Comment by lavandongen** [comment]
I had the same issue twice today. My Magic keyboard needed to be turned off and on again and then KE stopped working.

**Comment by flyinguard** [comment]
> I have been having this issue the past week or so, and it seems to be related to hitting CAPS LOCK too quickly next to other keypresses. It will halt all keyboard input until I unplug and replug the external keyboard. But then my mappings are inactive seemingly unless I reboot.

me too.

**Comment by wmertens** [comment]
Even after quitting karabiner-elements, there are a bunch of processes still active, and I can't kill them, they keep respawning. I also can't unload the kext, presumably because of the running processes.

Running `launchctl disable system/org.pqrs.karabiner.karabiner_kextd` doesn't do anything 😕

**Comment by domq** [comment]
Steps to reproduce:
1. Install Catalina on your Mac (mine is MacBook Pro (15-inch, 2018))
1. Install Karabiner Elements (I upgraded to 12.9.0 during my tests campaign)
1. Keep mashing the Caps Lock key until keyboard freezes.

It takes anywhere from a few seconds to 5 minutes for step 3 to happen on my system. Mashing other keys at the same time as Caps Lock, in particular dead accent keys, appears to speed up the crash. It is *not* necessary to hit any key that is being modified by Karabiner. The setting of Devices → Basic configuration → Manipulate LED appears to make no difference.

**Comment by genesy** [comment]
does this happen to all people using catalina? or is it just a bug that only happens in catalina? i was about to upgrade..

**Comment by wmertens** [comment]
Now it has gotten to the stage where I can't get keyboard-off nor complex modifications to work at all, even after rebooting multiple times :(

However! I just reinstalled karabiner 12.9.0 without restarting and everything works again… So hopefully that's a consistent workaround

**Comment by OItsMAK** [comment]
I realized that stupidly enough this can happen even if the screen is locked.
I locked the screen to clean my keyboard and then had to de/re-attach the dongle to just log in.

**Comment by OItsMAK** [comment]
Some other thing:

This last time it happened I uninstalled the app (`brew cask uninstall karabiner-elements`), and then instead of the usual reboot-install-configure steps, I did a `ps` to see what's up and I got this:
```Bash
❯ ps -ax | grep karabiner
  120 ??         0:00.00 (karabiner_grabbe)
99101 ttys000    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn karabiner
```

I got the same sort of output after killing everything before the uninstall:
```Bash
❯ ps -ax | grep karabiner
  118 ??        15:43.28 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
  120 ??        22:15.51 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
  596 ??         2:48.41 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_console_user_server
  602 ??         0:01.45 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
  603 ??         0:01.45 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
  606 ??         1:40.04 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_session_monitor
97523 ??         0:00.01 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_kextd
97645 ttys000    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn karabiner

~
❯ ps -ax | grep karabiner | gawk '{print $1}' | xargs sudo kill -9
kill: 97986: No such process # grep

~
❯ ps -ax | grep karabiner | gawk '{print $1}'
120
97991
97993
97994
97996
97997
97998
98087
```

It appears that everything is successfully killed, except for the `grabber`. I also tried force-quitting it through Activity Monitor but that didn't help either.

I would appreciate any solution that doesn't include a reboot. :)

**Comment by bnash2501** [comment]
Whoa! I thought it was just me having this issue. Glad to know it's karabiner. Anything we can do to help track the big down?
Also running 10.15 on a 2018 MBP. I use an external keyboard which triggers the issue as well. Guess I need to avoid caps lock.

**Comment by Jyosua** [comment]
This is happening to me as well. I'm on a 13-inch MacBook Pro 2017 model.

**Comment by pqvst** [comment]
Same issue here:
- Karabiner-Elements: 12.9.0
- MacBook Pro (15-inch, 2018)
- macOS: 10.15.4

Randomly pressing the caps lock will trigger the built-in keyboard to completely stop responding (touch bar still works though). Rebooting the systems resolves the issue until I accidentally hit caps lock again. For now I have disabled my caps lock key under System Preferences > Keyboard > Modifier Keys.

```
type:key_down        code:24         name:u               misc:
type:key_up          code:24         name:u               misc:
type:key_down        code:8          name:e               misc:
type:key_up          code:8          name:e               misc:
type:key_down        code:40         name:return_or_enter misc:
type:key_up          code:40         name:return_or_enter misc: 
type:key_down        code:57         name:caps_lock       misc:   <-- start mashing caps lock here
type:key_up          code:57         name:caps_lock       misc:
type:key_down        code:57         name:caps_lock       misc:
type:key_up          code:57         name:caps_lock       misc:
type:key_down        code:57         name:caps_lock       misc:
< keyboard frozen now >
```

Let me know if any other logs are needed.

**Comment by rabbbit** [comment]
+1, same symptoms, started to randomly happen a few days ago.

**Comment by piemasters** [comment]
I'd been having this issue since around October last year. It happened about twice a day for months and I thought it was a hardware issue until I saw this thread a few weeks ago (I thought I'd have one final search before I ripped the capslock key off).

The fix for me came from doing a PRAM/SMC reset.

I'm wondering if it was fixed in 12.9.0 and the reset removed whatever leftover setting that was still triggering it?

**Comment by goncha** [comment]
My situation (MacBook Pro 13-inch, Early 2015):

1. From macOS 10.15.3, updated Karabiner to latest version, everything is ok
2. Updated macOS to 10.15.4, the problem occured,  internal keyboard & trackpad didn't work after waking from sleep
3. Uninstalled Karabiner, the problem remained
4. Erased disk & reinstalled macOS,  without Karabiner, the problem remained
5. RESET NVRAM,  internal keyboard & trackpad work again. But still doesn't work after waking from sleep

**Comment by Thenio** [comment]
I have a same problem.
* Karabiner-Elements: 12.9.0
* MacBook Pro (13-inch, 2017)
* macOS: 10.15.4

I use only ONE modification in Karabiner. After last update (to 10.15.4) locked keyboard occurs more often. 
Solution of @Jyosua works :)

**Comment by PandaWood** [comment]
I possibly have the same problem, though this only happened when I got a new keyboard.
From a Ducky to a Varmilo - no amount of uninstalling, reconfiguring, restarting will bring my complex modifications back to working.

**Comment by nirvanadev** [comment]
I've had this issue several times since upgrading to Catalina, but with a different keyboard than mentioned by others. I'm using Logitech MXKeys. I've come to the conclusion that if not initially loaded last, karabiner will not work with complex modifications. To get things working, here is what I have been doing:

1. Disable any autorun or autostart settings if you have karabiner loading at startup.
2. Reboot the computer and choose not to reopen running apps.
3. Once rebooted, wait until everything has had a chance to start up and then launch karabiner.

Hopefully, these steps will help others. As soon as I do this, all my complex modifications work again.

**Comment by iwill** [comment]
> This is happening to me as well. I'm on a 13-inch MacBook Pro 2017 model.
> 
> A solution that fixed the problem when it occurs for me, without restarting was:
> `sudo pkill -f karabiner`
> 
> If you can either attach an external keyboard to type this, or use the "Emoji & Symbols" menu to enter the characters one by one (ugh).

"Show Keyboard Viewer" is better than "Emoji & Symbols".

**Comment by Console32** [comment]
I have the same problem, this seems to occur more frequently when using an accent key. I have a US Keyboard layout and use `OPTION` & `U` + U,O,A to print the German special characters.

If i mistype the A and hit caps instead the keyboard dies some times, sudo pkill does not work on my machine. I always have to restart.

**Comment by pliu-imentor** [comment]
when this happens, the caps lock on my MacBook Pro is lit, but the softkeys still work; I have to reboot to get the keyboard to work again. I'm uninstalling Karabiner until this is resolved

**Comment by hinder90** [comment]
Same issue... MacBook keyboard stops working altogether even after stopping Karabiner. Reboot is the only cure. Seems associated to caps lock. Also, I have no complex modifiers... just transposing a handful of function keys on my external keyboard.

**Comment by suleimanakbar** [comment]
Same issue, only a reboot fixes it.

Mac OS: 10.15.6
Karabiner-Elements: 12.10.0
Machine: Mid 2015 MBP 15
Keyboard: Microsoft Sculpt

**Comment by hejkerooo** [comment]
I use caps-lock constantly, after 2-3 hours keyboard stops working.

MacBook Pro 18 (i5 2.3 GHz, 16 GB ram)
MacOS: 10.15.6
Internal keyboard

**Comment by iwill** [comment]
> > This is happening to me as well. I'm on a 13-inch MacBook Pro 2017 model.
> > A solution that fixed the problem when it occurs for me, without restarting was:
> > `sudo pkill -f karabiner`
> > If you can either attach an external keyboard to type this, or use the "Emoji & Symbols" menu to enter the characters one by one (ugh).
> 
> "Show Keyboard Viewer" is better than "Emoji & Symbols".
> 
> But the command does not work for me, I'm editing this with Keyboard Viewer 🤪

Remapping Caps Lock to Control works for me:

    System Preferences > Keyboard > Keyboard > Modifier Keys... > Caps Lock Key: Control

**Comment by philipmarnef** [comment]
Same issue, on MacOS 10.15.6, Karabiner elements 12.10.0 with internal and external keyboard connected (both hang on CAPS LOCK).

Glad I found this thread, was worried it had to do with a battery replacement.

`sudo pkill -f karabiner` (via the keyboard viewer) only brings back the external keyboard.

After the crash the logs are filling up with these messages every second:
```
[...] [error] [observer] grabber_client error: No buffer space available
[...] [error] [console_user_server] grabber_client error: No buffer space available

```

**Comment by josephlim75** [comment]
Got the same issue on MacOS 10.15.6 Catalina.  After my computer went into lock screen, when I relogin, Karabiner stop working.  Perform all the `sudo pkill` and `sudo killall` on all the process, the 3 process `karabiner_grabber`, `karabiner_observer` and `karabiner_session_monitor` always came by itself.   After restarting Karabiner Element, I got the logs filling with the following messages:-

```
20-09-24 09:17:24.685] [error] [session_monitor] session_monitor_receiver_client error: No buffer space available
[2020-09-24 09:17:26.447] [error] [observer] grabber_client error: No buffer space available
```

**Comment by MuhammedZakir** [comment]
There is a beta version available which may solve your problem.

https://karabiner-elements.pqrs.org/docs/macos-big-sur/

**Comment by AKarbas** [comment]
It seems to have been resolved. Please add the version it was fixed since, or re-escalate if I'm wrong and it isn't.
Closing.

**Comment by ThinkSalat** [comment]
This is still happening for me on Big Sur 11.4, Karabiner-Elements v13.5.0.
