### ISSUE TITLE
KE 14.10.0 is flagged as malware

### ISSUE THREAD

**Issue by kgust** [pqrs-org/Karabiner-Elements#3235]
I have Cortex XDR installed on my MacBook Pro M1. It's required by company policy.

I attempted to upgrade to KE 14.10.0 and it was blocked by Cortex. It seems to think KE has wildfire malware.

<img width="1038" alt="Screen Shot 2022-09-25 at 5 04 43 PM" src="https://user-images.githubusercontent.com/1927402/192167815-5b4a350a-e999-4495-aa66-ed35c5f05d5f.png">

**Comment by maxelsen** [comment]
I can report the exact same issue.  Not sure what's triggering the alert.  Has to stay on 14.9 for the moment for me...

**Comment by Nikojoel** [comment]
Bump. Got the same issue

**Comment by tekezo** [comment]
It's a false positive. Please report to Cortex XDR.

WildFire Report Incorrect Verdict (virus false positive or false negative):
https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000Cm7KCAS

**Comment by maxelsen** [comment]
I was able to update Karabiner this morning to 14.10.  Looks like Cortex XDR has been corrected now.  Terrific stuff.

**Comment by acnebs** [comment]
I don't have Cortex XDR but the 14.10 update is still failing to install in the same way on my system (macOS 12.6)
