### ISSUE TITLE
one key not detectable on Microsoft Ergonomic Keyboard

### ISSUE THREAD

**Issue by kambala-decapitator** [pqrs-org/Karabiner-Elements#3453]
I have [Microsoft Ergonomic Keyboard LXM-00001](https://www.microsoft.com/en/accessories/products/keyboards/microsoft-ergonomic-keyboard?activetab=pivot:overviewtab). There's only one key that's completely undetectable by the Event Viewer: the button between sound and player controls.

I wanted to debug what's going on with that key, but didn't quite figure out how to do it. Even if I run Xcode as root it still doesn't let me to attach to karabiner_observer process.

P.S. Also some keys just send shortcuts instead of being detected as separate keys (see details in https://github.com/pqrs-org/Karabiner-Elements/issues/2460#issuecomment-1510279674), but not sure if that's possible.

**Comment by ipstone** [comment]
Reporting the same issue, not sure if the keyboard can be configured on a windows machine with https://support.microsoft.com/en-us/topic/mouse-and-keyboard-center-download-f5b10905-7887-eedb-2f1c-d0737a36a3b2

**Comment by ipstone** [comment]
I actually found the answer/solution: turn on the modification for this device as mentioned in this issue: https://github.com/pqrs-org/Karabiner-Elements/issues/2460

**Comment by kambala-decapitator** [comment]
> I actually found the answer/solution: turn on the modification for this device as mentioned in this issue: #2460

this issue is only about one specific key on the keyboard that is undetectable even with that setting on

**Comment by kambala-decapitator** [comment]
I've used test HID code to observe key events and found out that this key is actually detectable by macOS: https://stackoverflow.com/a/39834889/1971301 or https://github.com/akemin-dayo/IOKitHIDKeyboardTester/blob/master/IOKitHIDKeyboardTester/IOKitHIDKeyboardTester.m or anything similar.

```
static void Handle_DeviceEventCallback (void *inContext, IOReturn inResult, void *inSender, IOHIDValueRef value){
    IOHIDElementRef element = IOHIDValueGetElement(value);          // Keyboard pressed key

    uint32_t uniqueIdentifier = IOHIDElementGetCookie(element);     // Unique ID of key
    int elementValue = (int)IOHIDValueGetIntegerValue(value);       // Actual state of key (1=pressed)
    uint32_t scancode = IOHIDElementGetUsage(element);

    NSLog(@"Unique ID = %u; Value = %d; scancode = %u; usagePage = %u",
          uniqueIdentifier, elementValue, scancode, IOHIDElementGetUsagePage(element));
}
```

And output for that key is:
```
Unique ID = 289; Value = 0; scancode = 0; usagePage = 12
Unique ID = 676; Value = 1; scancode = 387; usagePage = 12
Unique ID = 288; Value = 387; scancode = 4294967295; usagePage = 12
Unique ID = 1324; Value = 271; scancode = 3; usagePage = 65280

Unique ID = 676; Value = 0; scancode = 387; usagePage = 12
Unique ID = 289; Value = 1; scancode = 0; usagePage = 12
Unique ID = 288; Value = 0; scancode = 4294967295; usagePage = 12
Unique ID = 1324; Value = 15; scancode = 3; usagePage = 65280
```

So this is `kHIDUsage_Csmr_ALConsumerControlConfiguration` under `kHIDPage_Consumer`. The question is how to add this special key to Karabiner.

P.S. once I enable "modify events" in Karabiner, my test app stops detecting the key.

**Comment by kambala-decapitator** [comment]
fixed by #3758

**Comment by LunaticoCR** [comment]
@kambala-decapitator I see your previous post saying this issue was fix by that pull request back in March. But I still can't get the media player button to work, I'm on version 15.0.0.
Did you get it to work, where you able to create a complex modification for it?

**Comment by LunaticoCR** [comment]
Never mind, I installed the beta 15.0.4 and on that build the media player is picked up by the viewer tool. But all my complex modifications stopped working. Need to investigate why, maybe needs a simple reboot....

**Comment by kambala-decapitator** [comment]
@LunaticoCR I'm on 15.0.0: the button itself works (opens Music.app), but not detected by Event Viewer. Haven't tried complex modifications with it.

**Comment by LunaticoCR** [comment]
Thanks @kambala-decapitator 
I made my complex modification work again, very strange issue:https://github.com/pqrs-org/Karabiner-Elements/issues/3701#issuecomment-2345737580

The button did work for me too, same as you describe. But I use YouTube Music so I want to make the button open that instead. With the beta build the button is now picked up by the viewer, so I think I can now map it to what I want.

**Comment by LunaticoCR** [comment]
Found it, this is the complex modification to get the media player button remapped to something else, in my case YouTube Music.
![image](https://github.com/user-attachments/assets/124e0f06-f88e-4636-b0c0-fc81edbe7c1e)


```json
{
    "description": "Map the keyboard media player key to open YouTube Music",
    "manipulators":
    [
        {
            "type": "basic",
            "from":
            {
                "consumer_key_code": "al_consumer_control_configuration",
                "modifiers":
                {
                    "optional":
                    [
                        "caps_lock"
                    ]
                }
            },
            "to":
            [
                {
                    "shell_command": "open -a '/Users/user_id/Applications/Brave Browser Apps.localized/YouTube Music.app'"
                }
            ]
        }
    ]
}
```
