### ISSUE TITLE
Binding CapsLock to Globe key does not work properly?

### ISSUE THREAD

**Issue by StianFlatby** [pqrs-org/Karabiner-Elements#3939]
macOS Sequoia introduces ctrl+globe+arrow organizing windows (which is now supported in Karabiner as well, thanks to the latest beta). 

Binding Caps Lock to the globe/fn button, so I can do ctrl+caps+arrow for organizing windows. But this doesn't work for all shortcuts, and I don't understand why.

Default **fn + ctrl + arrow** moves the current window to that arrow-direction. All directions work properly.
**CapsLock(->fn) + ctrl + up/down** works for moving up or down.
**CapsLock(->fn) + ctrl + left/right** does **nothing**.

<img width="788" alt="image" src="https://github.com/user-attachments/assets/10b9e6cf-3ad0-4a3b-b3b0-f611a700aa46">

For what it's worth, the same happens with the native "System Settings -> Keyboard -> Shortcuts -> Special keys" and mapping Caps Lock to Globe.
I have a wireless Apple keyboard with num pad (meaning the globe key is on "insert", which is why I want to put it on CapsLock).

**Comment by tekezo** [comment]
This issue is solved in the latest beta version.
https://github.com/pqrs-org/Karabiner-Elements/issues/3879#issuecomment-2381071748

**Comment by StianFlatby** [comment]
@tekezo It is not solved. This issue is for **Caps Lock**, not globe/fn, albeit related.
After binding CapsLock to Globe, shortcuts Caps+ctrl+left/right does not work the same ways as Globe+ctrl+left/right with the native window management in Sequoia. I feel like it should.

**Comment by marvelph** [comment]
I have this problem too.
I don't think this is a Karabiner-Elements bug, as it occurs even when the Globe and Caps Lock keys are swapped using a built-in feature of macOS.
I tried using Karabiner-Elements in the hope that this could be circumvented, but the result was the same as the macOS built-in functionality.
Should I give feedback to Apple?

**Comment by StianFlatby** [comment]
@marvelph Yeah, please do. I did the same.

**Comment by marvelph** [comment]
I provided feedback to Apple, but the issue was not fixed.
The problem persists in macOS Tahoe 26 as well.

**Comment by tekezo** [comment]
I’ve confirmed that window movement using Caps Lock (mapped to Fn) + Control + arrow keys works on my setup, so the issue may lie outside of Karabiner-Elements.
Tested with Karabiner-Elements v15.7.0 and macOS 26.1.

Settings and properly EventViewer result:

<img width="1100" height="732" alt="Image" src="https://github.com/user-attachments/assets/621f867b-9f13-4cfa-a0c8-9d5add207600" />
<img width="1101" height="703" alt="Image" src="https://github.com/user-attachments/assets/f6ed9b46-94d4-469a-aa22-6df28c6b6ed1" />
