### ISSUE TITLE
Caps Lock to Hyper Key not working on Sequoia

### ISSUE THREAD

**Issue by delucca** [pqrs-org/Karabiner-Elements#3949]
Hey everyone,

Before MacOS Sequioia and the latest update (15.1.0) of Karabiner, I use to have the following modification:
```
{
    "description": "Remap Caps Lock to Hyper Key if Being Hold",
    "manipulators": [
        {
            "from": {
                "key_code": "caps_lock",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "left_control",
                    "modifiers": ["left_command", "left_option", "left_shift"]
                }
            ],
            "to_if_alone": [{ "key_code": "caps_lock" }],
            "type": "basic"
        }
    ]
}
```

That modification basically mapped my Caps Lock key to Hyper only when hold

For some reason, after Sequoia + Karabiner v15.1.0 the "to_if_alone" is not working anymore (before 15.1.0 it used to work)

**Comment by llity** [comment]
I encountered the same problem

**Comment by AGitUser0001** [comment]
You need "hold_down_milliseconds": 100 because macOS no longer recognizes caps lock presses below 100ms.

**Comment by delucca** [comment]
> You need "hold_down_milliseconds": 100 because macOS no longer recognizes caps lock presses below 100ms.

perfect, that works.

I think by default that should already be the value, since anything below 100 will not work

**Comment by davmacario** [comment]
> You need "hold_down_milliseconds": 100 because macOS no longer recognizes caps lock presses below 100ms.

This solved it for me too.
For reference, here is my modification (I'm remapping caps lock to ctrl if held, and caps lock itself if tapped):

```json
{
    "description": "Caps Lock behaves as Caps Lock when tapped, but it behaves as a Left Control when held.",
    "manipulators": [
        {
            "from": {
                "key_code": "caps_lock",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "left_control",
                    "lazy": true
                }
            ],
            "to_if_alone": [
                {
                    "hold_down_milliseconds": 100,  // or higher
                    "key_code": "caps_lock"
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by smithjw** [comment]
I found that the `hold_down_milliseconds` didn't solve the issue for me (the remapping I use is LShift + RShift to Caps Lock). Looking at the Karabiner EventViewer application the behaviour I would see is Karabiner sends Caps Lock event, then after that configured delay, it would send another event Caps Lock event that disabled it.

To work around it, I'm now using the `from.simultaneous` which seems to resolve things for me:

``` json
{
    "description": "left_shift + right_shift to caps_lock",
    "manipulators": [
        {
            "from": {
                "modifiers": { "optional": ["any"] },
                "simultaneous": [
                    { "key_code": "left_shift" },
                    { "key_code": "right_shift" }
                ]
            },
            "to": [
                {
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock"
                },
                { "key_code": "vk_none" }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by bintoro** [comment]
@delucca So I guess this has been resolved, right?

**Comment by ericrbg-harmonic** [comment]
I still can't seem to get capslock to work properly; I just want to remap it to f13 to then do custom shortcuts, but copying davmacario's answer just leads to a capslock key that does caps locking, and does not trigger f13...

```
{
    "description": "Caps Lock behaves as Caps Lock when tapped, but it behaves as a Left Control when held.",
    "manipulators": [
        {
            "from": {
                "key_code": "caps_lock",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "f13",
                    "lazy": true
                }
            ],
            "to_if_alone": [
                {
                    "hold_down_milliseconds": 100, 
                    "key_code": "f13"
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by bintoro** [comment]
@ericrbg-harmonic The rule you posted makes no sense whatsoever, and your request is not related to the issue. If you simply want to remap Caps Lock to F13, then just create a simple modification via the UI. If you want to do something more complicated, I suggest you start with the documentation.

**Comment by ericrbg-harmonic** [comment]
@bintoro Sorry - I missed that the issue is a more specific issue than just "capslock doesn't work". The simple modification via the UI does not work, which is why I was trying other workarounds. At the moment, I just seem to be fully unable to remap capslock.

**Comment by bintoro** [comment]
@ericrbg-harmonic Works fine here. If you need support, post your setup and the output of EventViewer in the Discussions section. This issue has been resolved and should be closed.

**Comment by qizhengyang2017** [comment]
I added "hold_down_milliseconds": 100, so that pressing the Caps Lock key alone can trigger the Caps Lock function. However, there’s an unexpected issue: if I press another modifier key, such as Cmd, before pressing the Caps Lock key, it should still trigger the Hyper key function. But in reality, it behaves as a Caps Lock key instead.

```
{
    "description": "Remap Caps Lock to Hyper Key if Held",
    "enabled": false,
    "manipulators": [
        {
            "from": {
                "key_code": "caps_lock",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "left_control",
                    "modifiers": ["left_command", "left_option", "left_shift"]
                }
            ],
            "to_if_alone": [
                {
                    "hold_down_milliseconds": 100,
                    "key_code": "caps_lock"
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by devnoname120** [comment]
@smithjw What is the purpose of `{ "key_code": "vk_none" }`?

I arrived to a similar solution (which works) but I don't use `vk_none`:

```json
{
    "description": "Toggle caps_lock by simultaneously pressing left_shift and right_shift",
    "manipulators": [
        {
            "from": {
                "modifiers": { "optional": ["caps_lock"] },
                "simultaneous": [
                    { "key_code": "left_shift" },
                    { "key_code": "right_shift" }
                ],
                "simultaneous_options": { "detect_key_down_uninterruptedly": true }
            },
            "parameters": { "basic.simultaneous_threshold_milliseconds": 50000 },
            "to": [{ "key_code": "caps_lock" }],
            "type": "basic"
        }
    ]
}
```

**Edit**: ah I see `vk_none` is a workaround documented here: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/#investigate-key-names

Another (hopefully less hacky) solution that works for me is this:

```json
{
    "description": "Toggle caps_lock by pressing left_shift + right_shift at the same time",
    "manipulators": [
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "mandatory": ["right_shift"],
                    "optional": ["caps_lock"]
                }
            },
            "to_if_alone": [
                {
                    "halt": true,
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock",
                    "lazy": true
                }
            ],
            "to_if_held_down": [
                {
                    "halt": true,
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock",
                    "lazy": true
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "right_shift",
                "modifiers": {
                    "mandatory": ["left_shift"],
                    "optional": ["caps_lock"]
                }
            },
            "to_if_alone": [
                {
                    "halt": true,
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock",
                    "lazy": true
                }
            ],
            "to_if_held_down": [
                {
                    "halt": true,
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock",
                    "lazy": true
                }
            ],
            "type": "basic"
        }
    ]
}
```

It works both if you tap the second shift key or if you long press the second shift key. If you only need tap support the `to_if_held_down` blocks can be removed.

**Comment by devnoname120** [comment]
@smithjw Well actually much simpler the following works for me without any issues:

```json
{
    "description": "Disable the accidental keystroke prevention of Caps Lock",
    "manipulators": [
        {
            "from": {
                "key_code": "right_shift",
                "modifiers": {
                    "mandatory": ["left_shift"],
                    "optional": ["caps_lock"]
                }
            },
            "to": [
                {
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock"
                },
                { "key_code": "vk_none" }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "mandatory": ["right_shift"],
                    "optional": ["caps_lock"]
                }
            },
            "to": [
                {
                    "hold_down_milliseconds": 200,
                    "key_code": "caps_lock"
                },
                { "key_code": "vk_none" }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by mauroao** [comment]
> You need "hold_down_milliseconds": 100 because macOS no longer recognizes caps lock presses below 100ms.

Thanks !!!! Now the CapsLock is working again !!!! 🥇

**Comment by 0x3333** [comment]
I'm on Tahoe 26.5 (25F71), and my capslock modification doesn't work. It works OK on version 15.6. I upgraded today to 16.0 by mistake and same issue. I'll leave here my configuration, just in case.

```
            "complex_modifications": {
                "rules": [
                    {
                        "description": "Capslock + Key",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "caps_lock",
                                    "modifiers": { "optional": ["any"] }
                                },
                                "to": [
                                    {
                                        "set_variable": {
                                            "name": "caps_lock_pressed",
                                            "value": 1
                                        }
                                    }
                                ],
                                "to_after_key_up": [
                                    {
                                        "set_variable": {
                                            "name": "caps_lock_pressed",
                                            "value": 0
                                        }
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "hold_down_milliseconds": 100,
                                        "key_code": "caps_lock"
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "conditions": [
                                    {
                                        "name": "caps_lock_pressed",
                                        "type": "variable_if",
                                        "value": 1
                                    }
                                ],
                                "from": {
                                    "key_code": "1",
                                    "modifiers": { "optional": ["any"] }
                                },
                                "to": [{ "key_code": "f1" }],
                                "type": "basic"
                            },
...
```
