### ISSUE TITLE
Fn+other key will re-trigger single Fn

### ISSUE THREAD

**Issue by huaium** [pqrs-org/Karabiner-Elements#3971]
Fn+other key will re-trigger single Fn.
For configuration, I only swap the function of caps lock and esc without any changes related to Fn.
Currently using macOS 15.0.1 (24A348)

**Comment by Jonathan-Landeed** [comment]
I'm getting the same issue. Mac uses fn for the emoji picker, but suppresses that when you use fn with another key like left/right arrow or the the function keys (when using them as standard function keys).

When I turn on karabiner elements, fn+left/right arrow works properly, but the fn+F1/etc no longer suppresses the emoji picker all the time. It actually depends on how long I hold fn before pressing a function key. If its a short hold, the emoji picker appears. If its a long hold, it works properly.

**Comment by tekezo** [comment]
I cannot reproduce the issue on my end.
Let me know the events in EventViewer when the issue occurs.

<img width="1095" alt="Screenshot 2024-11-20 at 9 07 22" src="https://github.com/user-attachments/assets/29434c59-d6d0-4e38-a21a-ef7c4792e2a4">

**Comment by Jonathan-Landeed** [comment]
The first one I did quickly and it triggered the emoji picker. The second one I did slowly and it did not trigger the emoji picker.
![Screenshot 2024-11-19 at 4 47 44 PM (2)](https://github.com/user-attachments/assets/6f5e0c7b-be21-4295-b993-979bf8e6419d)

**Comment by huaium** [comment]
> The first one I did quickly and it triggered the emoji picker. The second one I did slowly and it did not trigger the emoji picker.
> 
> ![Screenshot 2024-11-19 at 4 47 44 PM (2)](https://github.com/user-attachments/assets/6f5e0c7b-be21-4295-b993-979bf8e6419d)
> 
> 

Thank you for providing screenshot. I did find that this is related to the duration of holding Fn, and typically happens when combining with volume +/-.

**Comment by Jonathan-Landeed** [comment]
The problem is that pressing volume_decrement is FIRST causing an `up` on keyboard_fn, even if I'm holding it down, leading to down>up>down>up.

Turning off my keyboard in karabiner elements, I get the correct down>down>up>up

<img width="1095" alt="Screenshot 2024-11-19 at 8 11 39 PM" src="https://github.com/user-attachments/assets/c7d84bb4-cdc7-4208-af1a-2f151460e4c8">

Interestingly, fn+left/right does the correct down>down>up>up regardless of whether karabiner elements is turned on.
<img width="814" alt="Screenshot 2024-11-19 at 8 16 06 PM" src="https://github.com/user-attachments/assets/5578c5c9-e961-4288-8885-bd873dcdce0c">
<img width="788" alt="Screenshot 2024-11-19 at 8 17 12 PM" src="https://github.com/user-attachments/assets/0aa21d41-94e9-43e6-8ed1-e6fd2ca52d81">

**Comment by tekezo** [comment]
Thank you for detailed information.
I finally could reproduce this issue.

I addressed this issue at the latest beta version (v15.3.3).
Please confirm it.

# Note

There is one limitation: the fn key will be tapped if the following conditions are met:

- "Use all F1, F2, etc. keys as standard function keys" is enabled.
- Any of fn+f1 to fn+f12 is remapped to a regular f1–f12 key (e.g., remapping fn+f12 to f3).

# How to upgrade to the latest beta version
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by Jonathan-Landeed** [comment]
Wonderful! And yes, still seeing it on my F6 because I don't think Karabiner can map that directly to Do Not Disturb, but I never use it anyway. Works perfect for the rest. Thank you!
