### ISSUE TITLE
keyboard unresponsive when karabiner elements is active except for the remapped key

### ISSUE THREAD

**Issue by heh372** [pqrs-org/Karabiner-Elements#4333]
Whenever "modify events" is on for my keyboard in the devices tab (which as you know has to be enabled for the modification to work) my entire keyboard gets disabled except for the remapped up arrow key and the power button, every other key becomes completely unresponsive.

I have tried uninstalling and reinstalling Karabiner completely, tried restarting, tried deleting the config files, tried unplugging everything, nothing has worked so far... One interesting thing I discovered though, when I was using the EventViewer to test the keyboard, the key presses actually registered fine on the app, but for some reason they weren't doing anything. (i.e., I would press "a" and it would show "{key_code:a}" or whatever as it would without the modification active except it wouldn't type out anything.)

Some info about my device, it's a 2017 Macbook Air 13'' running macOS 12, the only other software I have installed is Logitech G hub but I don't think it's the problem because I never use it and the issue persists even without it. From what I've learned other software could interfere with it.

Any help is appreciated

**Comment by tekezo** [comment]
It doesn't handle keyboards properly when the Logitech driver or other third vendor drivers are active.
Using a different vendor's keyboard or properly uninstalling the Logitech driver should resolve the issue.

**Comment by heh372** [comment]
I uninstalled everything related to Logitech and it still doesnt work

**Comment by heh372** [comment]
ok, i figured it out, all i had to do was sudo killall any input driver processes there were on activity monitor
